# Generated by Django 5.2.10 on 2026-03-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(choices=[('Apple', 'Apple'), ('Samsung', 'Samsung'), ('Google', 'Google'), ('OnePlus', 'OnePlus'), ('Xiaomi', 'Xiaomi'), ('OPPO', 'OPPO'), ('Vivo', 'Vivo'), ('Realme', 'Realme'), ('Huawei', 'Huawei'), ('Motorola', 'Motorola')], max_length=50)),
                ('model_name', models.CharField(max_length=200)),
                ('os', models.CharField(choices=[('Android', 'Android'), ('iOS', 'iOS'), ('Windows Phone', 'Windows Phone')], max_length=20)),
                ('processor', models.CharField(max_length=200)),
                ('ram', models.CharField(max_length=50)),
                ('storage', models.CharField(max_length=50)),
                ('display', models.CharField(max_length=100)),
                ('camera', models.CharField(blank=True, max_length=200)),
                ('battery', models.CharField(blank=True, max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('image', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
